// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srzoyvpyytvvdlctgdaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyem95dnB5eXR2dmRsY3RnZGF6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NzM0MzcsImV4cCI6MjA3MzQ0OTQzN30.YKTV0UAIKVBiDoUVRckBYSEu2whswID1toJ8IOGtjKg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});